package model.bc.views;

import model.shared.extensions.ExtViewObjectImpl;

import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 24 13:26:05 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CcityStaticImpl extends ExtViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CcityStaticImpl() {
    }
}

