package model.bc.views;

import model.shared.extensions.ExtViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 27 02:56:47 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CreditCardsImpl extends ExtViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CreditCardsImpl() {
    }
}

