package model.bc.views;

import model.shared.extensions.ExtViewObjectImpl;

import oracle.jbo.Key;
import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 27 03:03:03 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class payTypeStaticImpl extends ExtViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public payTypeStaticImpl() {
    }
    
    public String getPayTypeName(Number i){
        System.out.println("Inside the class");
        this.first();
        Row r = this.getRow(new Key(new Object[]{i}));
        String val = (String) r.getAttribute("Type");
        return val;
        
    }
}

